
name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          project_name: CxMichaelF-jvl-demo-GH_Action
          cx_tenant: dp_wp_na
          base_uri: https://ast.checkmarx.net/
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          # DEFINE SCANNER:
          # scan_types: sast,sca,kics
          # DEFINE BRANCH:
          branch: main
          # DEFINE THRESHOLDS:
          # additional_params: --thresholdd "sast-high=3; sca-high=1;kics-high=1" 
